//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ExchangeService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PracticalWcf/Exchange/Trade")]
    [System.SerializableAttribute()]
    public partial class Trade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ParticipantField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuotedPriceField;
        
        private string TickerField;
        
        private char TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TradeTimeField;
        
        private string PublisherField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Participant
        {
            get
            {
                return this.ParticipantField;
            }
            set
            {
                this.ParticipantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QuotedPrice
        {
            get
            {
                return this.QuotedPriceField;
            }
            set
            {
                this.QuotedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ticker
        {
            get
            {
                return this.TickerField;
            }
            set
            {
                this.TickerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> TradeTime
        {
            get
            {
                return this.TradeTimeField;
            }
            set
            {
                this.TradeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService", ConfigurationName="WcfClient.ExchangeService.TradeService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface TradeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarket", ReplyAction="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarketRespo" +
            "nse")]
        decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TradeServiceChannel : WcfClient.ExchangeService.TradeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TradeServiceClient : System.ServiceModel.ClientBase<WcfClient.ExchangeService.TradeService>, WcfClient.ExchangeService.TradeService
    {
        
        public TradeServiceClient()
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade)
        {
            return base.Channel.TradeSecurityAtMarket(trade);
        }
    }
}
