//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ExchangeService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService", ConfigurationName="WcfClient.ExchangeService.TradeService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface TradeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarket", ReplyAction="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarketRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4324.16")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PracticalWcf/Exchange/TradeService")]
    public partial class Trade
    {
        
        private char typeField;
        
        private string publisherField;
        
        private decimal quotedPriceField;
        
        private int quantityField;
        
        private System.DateTime executionTimeField;
        
        private decimal executionAmountField;
        
        private string tickerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public char Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Publisher
        {
            get
            {
                return this.publisherField;
            }
            set
            {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal QuotedPrice
        {
            get
            {
                return this.quotedPriceField;
            }
            set
            {
                this.quotedPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ExecutionTime
        {
            get
            {
                return this.executionTimeField;
            }
            set
            {
                this.executionTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal ExecutionAmount
        {
            get
            {
                return this.executionAmountField;
            }
            set
            {
                this.executionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ticker
        {
            get
            {
                return this.tickerField;
            }
            set
            {
                this.tickerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TradeServiceChannel : WcfClient.ExchangeService.TradeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TradeServiceClient : System.ServiceModel.ClientBase<WcfClient.ExchangeService.TradeService>, WcfClient.ExchangeService.TradeService
    {
        
        public TradeServiceClient()
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade)
        {
            return base.Channel.TradeSecurityAtMarket(trade);
        }
    }
}
