//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ExchangeService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PracticalWcf/Exchange/Trade")]
    [System.SerializableAttribute()]
    public partial class Trade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ParticipantField;
        
        private int QuantityField;
        
        private string TickerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuotedPriceField;
        
        private char TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TradeTimeField;
        
        private string PublisherField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Participant
        {
            get
            {
                return this.ParticipantField;
            }
            set
            {
                this.ParticipantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ticker
        {
            get
            {
                return this.TickerField;
            }
            set
            {
                this.TickerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal QuotedPrice
        {
            get
            {
                return this.QuotedPriceField;
            }
            set
            {
                this.QuotedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public char Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> TradeTime
        {
            get
            {
                return this.TradeTimeField;
            }
            set
            {
                this.TradeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PracticalWcf/Exchange/Execution")]
    [System.SerializableAttribute()]
    public partial class Execution : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExecutionAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SettleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfClient.ExchangeService.Trade TradeSubmittedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExecutionAmount
        {
            get
            {
                return this.ExecutionAmountField;
            }
            set
            {
                this.ExecutionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Participant
        {
            get
            {
                return this.ParticipantField;
            }
            set
            {
                this.ParticipantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SettleDate
        {
            get
            {
                return this.SettleDateField;
            }
            set
            {
                this.SettleDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfClient.ExchangeService.Trade TradeSubmitted
        {
            get
            {
                return this.TradeSubmittedField;
            }
            set
            {
                this.TradeSubmittedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PracticalWcf/Exchange", ConfigurationName="WcfClient.ExchangeService.TradeService")]
    public interface TradeService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (TradeSecurityRequest) of message TradeSecurityRequest does not match the default value (TradeSecurity)
        [System.ServiceModel.OperationContractAttribute(Action="http://PracticalWcf/Exchange/TradeService/TradeSecurityAtMarket", ReplyAction="http://PracticalWcf/Exchange/TradeService/TradeSecurityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://PracticalWcf/Exchange/TradeService/TradeSecurityArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        WcfClient.ExchangeService.TradeSecurityResponse TradeSecurity(WcfClient.ExchangeService.TradeSecurityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TradeSecurityRequest", WrapperNamespace="http://PracticalWcf/Exchange", IsWrapped=true)]
    public partial class TradeSecurityRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://PracticalWcf/Exchange")]
        public string Participant;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://PracticalWcf/Exchange")]
        public string Publisher;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://PracticalWcf/Exchange")]
        public string Ticker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://PracticalWcf/Exchange", Order=0)]
        public WcfClient.ExchangeService.Trade TradeItem;
        
        public TradeSecurityRequest()
        {
        }
        
        public TradeSecurityRequest(string Participant, string Publisher, string Ticker, WcfClient.ExchangeService.Trade TradeItem)
        {
            this.Participant = Participant;
            this.Publisher = Publisher;
            this.Ticker = Ticker;
            this.TradeItem = TradeItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TradeSecurityResponse", WrapperNamespace="http://PracticalWcf/Exchange", IsWrapped=true)]
    public partial class TradeSecurityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://PracticalWcf/Exchange", Order=0)]
        public WcfClient.ExchangeService.Execution ExecutionReport;
        
        public TradeSecurityResponse()
        {
        }
        
        public TradeSecurityResponse(WcfClient.ExchangeService.Execution ExecutionReport)
        {
            this.ExecutionReport = ExecutionReport;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TradeServiceChannel : WcfClient.ExchangeService.TradeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TradeServiceClient : System.ServiceModel.ClientBase<WcfClient.ExchangeService.TradeService>, WcfClient.ExchangeService.TradeService
    {
        
        public TradeServiceClient()
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        WcfClient.ExchangeService.TradeSecurityResponse WcfClient.ExchangeService.TradeService.TradeSecurity(WcfClient.ExchangeService.TradeSecurityRequest request)
        {
            return base.Channel.TradeSecurity(request);
        }
        
        public WcfClient.ExchangeService.Execution TradeSecurity(string Participant, string Publisher, string Ticker, WcfClient.ExchangeService.Trade TradeItem)
        {
            WcfClient.ExchangeService.TradeSecurityRequest inValue = new WcfClient.ExchangeService.TradeSecurityRequest();
            inValue.Participant = Participant;
            inValue.Publisher = Publisher;
            inValue.Ticker = Ticker;
            inValue.TradeItem = TradeItem;
            WcfClient.ExchangeService.TradeSecurityResponse retVal = ((WcfClient.ExchangeService.TradeService)(this)).TradeSecurity(inValue);
            return retVal.ExecutionReport;
        }
    }
}
