//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetComClient.OldHorse2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/3B26F4CA-E839-4AB6-86D4-AADB0A8AADA5", ConfigurationName="DotNetComClient.OldHorse2.IPositionManagement", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IPositionManagement
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/3B26F4CA-E839-4AB6-86D4-AADB0A8AADA5/IPositionManagement/Updat" +
            "ePosition", ReplyAction="http://tempuri.org/3B26F4CA-E839-4AB6-86D4-AADB0A8AADA5/IPositionManagement/Updat" +
            "ePositionResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        long UpdatePosition(string ticker, long quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/3B26F4CA-E839-4AB6-86D4-AADB0A8AADA5/IPositionManagement/GetQu" +
            "antity", ReplyAction="http://tempuri.org/3B26F4CA-E839-4AB6-86D4-AADB0A8AADA5/IPositionManagement/GetQu" +
            "antityResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        long GetQuantity(string ticker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPositionManagementChannel : DotNetComClient.OldHorse2.IPositionManagement, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PositionManagementClient : System.ServiceModel.ClientBase<DotNetComClient.OldHorse2.IPositionManagement>, DotNetComClient.OldHorse2.IPositionManagement
    {
        
        public PositionManagementClient()
        {
        }
        
        public PositionManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PositionManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PositionManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PositionManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public long UpdatePosition(string ticker, long quantity)
        {
            return base.Channel.UpdatePosition(ticker, quantity);
        }
        
        public long GetQuantity(string ticker)
        {
            return base.Channel.GetQuantity(ticker);
        }
    }
}
