//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ExchangeService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/ExchangeService")]
    [System.SerializableAttribute()]
    public partial class Trade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal _executionAmountField;
        
        private string _participantField;
        
        private string _publisherField;
        
        private int _quantityField;
        
        private decimal _quotedPriceField;
        
        private string _tickerField;
        
        private System.DateTime _tradeTimeField;
        
        private char _typeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _executionAmount
        {
            get
            {
                return this._executionAmountField;
            }
            set
            {
                this._executionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _participant
        {
            get
            {
                return this._participantField;
            }
            set
            {
                this._participantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _publisher
        {
            get
            {
                return this._publisherField;
            }
            set
            {
                this._publisherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _quantity
        {
            get
            {
                return this._quantityField;
            }
            set
            {
                this._quantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _quotedPrice
        {
            get
            {
                return this._quotedPriceField;
            }
            set
            {
                this._quotedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ticker
        {
            get
            {
                return this._tickerField;
            }
            set
            {
                this._tickerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _tradeTime
        {
            get
            {
                return this._tradeTimeField;
            }
            set
            {
                this._tradeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char _type
        {
            get
            {
                return this._typeField;
            }
            set
            {
                this._typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService", ConfigurationName="WcfClient.ExchangeService.TradeService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface TradeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarket", ReplyAction="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarketRespo" +
            "nse")]
        decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TradeServiceChannel : WcfClient.ExchangeService.TradeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TradeServiceClient : System.ServiceModel.ClientBase<WcfClient.ExchangeService.TradeService>, WcfClient.ExchangeService.TradeService
    {
        
        public TradeServiceClient()
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade)
        {
            return base.Channel.TradeSecurityAtMarket(trade);
        }
    }
}
