//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.308
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickReturn
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StockQuote : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AverageVolumeField;
        
        private decimal ChangeField;
        
        private string CompanyNameField;
        
        private decimal EarningsPerShareField;
        
        private decimal LastTradeField;
        
        private double MarketCapitalField;
        
        private decimal PreviousCloseField;
        
        private decimal PriceEarningRatioField;
        
        private string TickerSymbolField;
        
        private decimal _52WkHighField;
        
        private decimal _52WkLowField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AverageVolume
        {
            get
            {
                return this.AverageVolumeField;
            }
            set
            {
                this.AverageVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Change
        {
            get
            {
                return this.ChangeField;
            }
            set
            {
                this.ChangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EarningsPerShare
        {
            get
            {
                return this.EarningsPerShareField;
            }
            set
            {
                this.EarningsPerShareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LastTrade
        {
            get
            {
                return this.LastTradeField;
            }
            set
            {
                this.LastTradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MarketCapital
        {
            get
            {
                return this.MarketCapitalField;
            }
            set
            {
                this.MarketCapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreviousClose
        {
            get
            {
                return this.PreviousCloseField;
            }
            set
            {
                this.PreviousCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceEarningRatio
        {
            get
            {
                return this.PriceEarningRatioField;
            }
            set
            {
                this.PriceEarningRatioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TickerSymbol
        {
            get
            {
                return this.TickerSymbolField;
            }
            set
            {
                this.TickerSymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="52WkHigh")]
        public decimal _52WkHigh
        {
            get
            {
                return this._52WkHighField;
            }
            set
            {
                this._52WkHighField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="52WkLow")]
        public decimal _52WkLow
        {
            get
            {
                return this._52WkLowField;
            }
            set
            {
                this._52WkLowField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IQuickReturnQuoteService")]
public interface IQuickReturnQuoteService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuickReturnQuoteService/GetPortfolio", ReplyAction="http://tempuri.org/IQuickReturnQuoteService/GetPortfolioResponse")]
    QuickReturn.StockQuote[] GetPortfolio(string[] portfolioTickers);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuickReturnQuoteService/GetQuote", ReplyAction="http://tempuri.org/IQuickReturnQuoteService/GetQuoteResponse")]
    QuickReturn.StockQuote GetQuote(string ticker);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IQuickReturnQuoteServiceChannel : IQuickReturnQuoteService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class QuickReturnQuoteServiceClient : System.ServiceModel.ClientBase<IQuickReturnQuoteService>, IQuickReturnQuoteService
{
    
    public QuickReturnQuoteServiceClient()
    {
    }
    
    public QuickReturnQuoteServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public QuickReturnQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public QuickReturnQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public QuickReturnQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public QuickReturn.StockQuote[] GetPortfolio(string[] portfolioTickers)
    {
        return base.Channel.GetPortfolio(portfolioTickers);
    }
    
    public QuickReturn.StockQuote GetQuote(string ticker)
    {
        return base.Channel.GetQuote(ticker);
    }
}
