//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ExchangeService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService")]
    [System.SerializableAttribute()]
    public partial class Trade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TickerField;
        
        private char TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipantField;
        
        private decimal QuotedPriceField;
        
        private int QuantityField;
        
        private System.DateTime TradeTimeField;
        
        private decimal ExecutionAmountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ticker
        {
            get
            {
                return this.TickerField;
            }
            set
            {
                this.TickerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Participant
        {
            get
            {
                return this.ParticipantField;
            }
            set
            {
                this.ParticipantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal QuotedPrice
        {
            get
            {
                return this.QuotedPriceField;
            }
            set
            {
                this.QuotedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime TradeTime
        {
            get
            {
                return this.TradeTimeField;
            }
            set
            {
                this.TradeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal ExecutionAmount
        {
            get
            {
                return this.ExecutionAmountField;
            }
            set
            {
                this.ExecutionAmountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService", ConfigurationName="WcfClient.ExchangeService.TradeService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface TradeService
    {
        
        // CODEGEN: Generating message contract since element name trade from namespace http://PracticalWcf/Exchange/TradeService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarket", ReplyAction="http://PracticalWcf/Exchange/TradeService/TradeService/TradeSecurityAtMarketRespo" +
            "nse")]
        WcfClient.ExchangeService.TradeSecurityAtMarketResponse TradeSecurityAtMarket(WcfClient.ExchangeService.TradeSecurityAtMarketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TradeSecurityAtMarketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TradeSecurityAtMarket", Namespace="http://PracticalWcf/Exchange/TradeService", Order=0)]
        public WcfClient.ExchangeService.TradeSecurityAtMarketRequestBody Body;
        
        public TradeSecurityAtMarketRequest()
        {
        }
        
        public TradeSecurityAtMarketRequest(WcfClient.ExchangeService.TradeSecurityAtMarketRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService")]
    public partial class TradeSecurityAtMarketRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WcfClient.ExchangeService.Trade trade;
        
        public TradeSecurityAtMarketRequestBody()
        {
        }
        
        public TradeSecurityAtMarketRequestBody(WcfClient.ExchangeService.Trade trade)
        {
            this.trade = trade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TradeSecurityAtMarketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TradeSecurityAtMarketResponse", Namespace="http://PracticalWcf/Exchange/TradeService", Order=0)]
        public WcfClient.ExchangeService.TradeSecurityAtMarketResponseBody Body;
        
        public TradeSecurityAtMarketResponse()
        {
        }
        
        public TradeSecurityAtMarketResponse(WcfClient.ExchangeService.TradeSecurityAtMarketResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://PracticalWcf/Exchange/TradeService")]
    public partial class TradeSecurityAtMarketResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal TradeSecurityAtMarketResult;
        
        public TradeSecurityAtMarketResponseBody()
        {
        }
        
        public TradeSecurityAtMarketResponseBody(decimal TradeSecurityAtMarketResult)
        {
            this.TradeSecurityAtMarketResult = TradeSecurityAtMarketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TradeServiceChannel : WcfClient.ExchangeService.TradeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TradeServiceClient : System.ServiceModel.ClientBase<WcfClient.ExchangeService.TradeService>, WcfClient.ExchangeService.TradeService
    {
        
        public TradeServiceClient()
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        WcfClient.ExchangeService.TradeSecurityAtMarketResponse WcfClient.ExchangeService.TradeService.TradeSecurityAtMarket(WcfClient.ExchangeService.TradeSecurityAtMarketRequest request)
        {
            return base.Channel.TradeSecurityAtMarket(request);
        }
        
        public decimal TradeSecurityAtMarket(WcfClient.ExchangeService.Trade trade)
        {
            WcfClient.ExchangeService.TradeSecurityAtMarketRequest inValue = new WcfClient.ExchangeService.TradeSecurityAtMarketRequest();
            inValue.Body = new WcfClient.ExchangeService.TradeSecurityAtMarketRequestBody();
            inValue.Body.trade = trade;
            WcfClient.ExchangeService.TradeSecurityAtMarketResponse retVal = ((WcfClient.ExchangeService.TradeService)(this)).TradeSecurityAtMarket(inValue);
            return retVal.Body.TradeSecurityAtMarketResult;
        }
    }
}
