//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://QuickReturns", ClrNamespace = "quickreturns")]

namespace quickreturns
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Quote : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private decimal AskField;

        private decimal BidField;

        private string PublisherField;

        private string TickerField;

        private System.DateTime UpdateDateTimeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ask
        {
            get
            {
                return this.AskField;
            }
            set
            {
                this.AskField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Bid
        {
            get
            {
                return this.BidField;
            }
            set
            {
                this.BidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticker
        {
            get
            {
                return this.TickerField;
            }
            set
            {
                this.TickerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDateTime
        {
            get
            {
                return this.UpdateDateTimeField;
            }
            set
            {
                this.UpdateDateTimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://QuickReturns", ConfigurationName = "ITradeService")]
public interface ITradeService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://QuickReturns/ITradeService/GetQuote", ReplyAction = "http://QuickReturns/ITradeService/GetQuoteResponse")]
    quickreturns.Quote GetQuote(string ticker);

    [System.ServiceModel.OperationContractAttribute(Action = "http://QuickReturns/ITradeService/PublishQuote", ReplyAction = "http://QuickReturns/ITradeService/PublishQuoteResponse")]
    void PublishQuote(quickreturns.Quote quote);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITradeServiceChannel : ITradeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TradeServiceClient : System.ServiceModel.ClientBase<ITradeService>, ITradeService
{

    public TradeServiceClient()
    {
    }

    public TradeServiceClient(string endpointConfigurationName)
        :
            base(endpointConfigurationName)
    {
    }

    public TradeServiceClient(string endpointConfigurationName, string remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public TradeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public TradeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(binding, remoteAddress)
    {
    }

    public quickreturns.Quote GetQuote(string ticker)
    {
        return base.Channel.GetQuote(ticker);
    }

    public void PublishQuote(quickreturns.Quote quote)
    {
        base.Channel.PublishQuote(quote);
    }
}
